// <auto-generated />
using System;
using FurnitureOnlineShop.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FurnitureOnlineShop.Persistence.Migrations
{
    [DbContext(typeof(FurnitureOnlineShopDBContext))]
    [Migration("20240213055344_Mig-db-int")]
    partial class Migdbint
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FurnitureOnlineShop.Domain.Entities.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdentityUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsFinaly")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IdentityUserId");

                    b.ToTable("Carts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdentityUserId = "8e445865-a24d-4543-a6c6-9443d048cdb9",
                            IsFinaly = true,
                            LastModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("FurnitureOnlineShop.Domain.Entities.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CartId = 1,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 1,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 2,
                            CartId = 1,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 2,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 3,
                            CartId = 1,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 3,
                            Quantity = 3
                        },
                        new
                        {
                            Id = 4,
                            CartId = 1,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 4,
                            Quantity = 3
                        });
                });

            modelBuilder.Entity("FurnitureOnlineShop.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("QuantityInStock")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 2, 13, 5, 53, 44, 228, DateTimeKind.Utc).AddTicks(5088),
                            Description = "Nordic Chair, a timeless blend of minimalist design and unparalleled comfort. Crafted with meticulous attention to detail, this chair embodies the essence of Scandinavian elegance, making it a perfect addition to any modern living space.\r\n\r\nDesigned for both style and functionality, the Nordic Chair features clean lines, gentle curves, and a sleek silhouette that effortlessly complements any interior décor. Its minimalist frame is expertly crafted from high-quality wood, ensuring durability and stability for years to come.",
                            ImagePath = "/images/product-1.png",
                            LastModifiedDate = new DateTime(2024, 2, 13, 5, 53, 44, 228, DateTimeKind.Utc).AddTicks(5092),
                            Price = 50m,
                            QuantityInStock = 9,
                            Title = "Nordic Chair"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 2, 13, 5, 53, 44, 228, DateTimeKind.Utc).AddTicks(5102),
                            Description = "Kruzo Aero Chair, where innovation meets sophistication in a seamless fusion of style and functionality. Engineered with cutting-edge design and premium materials, this chair redefines modern seating, offering unparalleled comfort and aesthetic appeal.\r\n\r\nCrafted with precision, the Kruzo Aero Chair features a sleek and aerodynamic silhouette that exudes contemporary elegance. Its distinctive design elements, including fluid lines and a curved backrest, create a sense of dynamic movement, making it a striking focal point in any space.",
                            ImagePath = "/images/product-2.png",
                            LastModifiedDate = new DateTime(2024, 2, 13, 5, 53, 44, 228, DateTimeKind.Utc).AddTicks(5103),
                            Price = 78m,
                            QuantityInStock = 14,
                            Title = "Kruzo Aero Chair"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 2, 13, 5, 53, 44, 228, DateTimeKind.Utc).AddTicks(5107),
                            Description = "Ergonomic Chair, meticulously designed to prioritize your comfort, health, and productivity. Crafted with precision engineering and ergonomic principles, this chair offers exceptional support and adaptability for extended periods of sitting.\r\n\r\nThe Ergonomic Chair features an innovative design that contours to the natural curvature of your body, providing optimal lumbar support and promoting healthy posture. Its adjustable features, including lumbar support, seat depth, armrests, and height, ensure customizable comfort tailored to your individual needs.",
                            ImagePath = "/images/product-3.png",
                            LastModifiedDate = new DateTime(2024, 2, 13, 5, 53, 44, 228, DateTimeKind.Utc).AddTicks(5109),
                            Price = 43m,
                            QuantityInStock = 5,
                            Title = "Ergonomic Chair"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 2, 13, 5, 53, 44, 228, DateTimeKind.Utc).AddTicks(5112),
                            Description = "luxurious Sofa, a masterpiece of comfort and style that transforms any living space into a haven of relaxation and elegance. Crafted with the finest materials and meticulous attention to detail, this sofa offers unparalleled comfort, durability, and timeless beauty.\r\n\r\nDesigned for both aesthetics and functionality, our Sofa boasts a timeless silhouette with clean lines and plush cushions, creating a harmonious balance of modern sophistication and inviting comfort. Its sturdy frame, crafted from high-quality hardwood, ensures stability and longevity, promising years of enjoyment for you and your loved ones.",
                            ImagePath = "/images/sofa.png",
                            LastModifiedDate = new DateTime(2024, 2, 13, 5, 53, 44, 228, DateTimeKind.Utc).AddTicks(5114),
                            Price = 57m,
                            QuantityInStock = 10,
                            Title = "luxurious Sofa"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("IdentityUser");
                });

            modelBuilder.Entity("FurnitureOnlineShop.Domain.Entities.Cart", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "IdentityUser")
                        .WithMany()
                        .HasForeignKey("IdentityUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdentityUser");
                });

            modelBuilder.Entity("FurnitureOnlineShop.Domain.Entities.CartItem", b =>
                {
                    b.HasOne("FurnitureOnlineShop.Domain.Entities.Cart", "Cart")
                        .WithMany("cartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FurnitureOnlineShop.Domain.Entities.Product", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("FurnitureOnlineShop.Domain.Entities.Cart", b =>
                {
                    b.Navigation("cartItems");
                });

            modelBuilder.Entity("FurnitureOnlineShop.Domain.Entities.Product", b =>
                {
                    b.Navigation("CartItems");
                });
#pragma warning restore 612, 618
        }
    }
}
